#!/usr/bin/env node
// 南湖前端独有商户坐标补全（W3.1 · 2026-08-15）
// 目的：robin-99 / web-stalls 的 127 家南湖店坐标全 null（此前守「不伪造坐标」红线只留空）；
//       现在用高德 geocode 解析**真实坐标**（地址 → 坐标，非编造），并带 coordsSource:'geocode' 审计标记。
// 红线：坐标全部来自高德解析（真实）；解析失败/无地址 → 保持 null 不硬造；不提升 dataConfidence。
// 产物：h5/src/data/extras-coords.json（all-merchants.js 合并时应用，源数据文件不动）。
// 用法：node scripts/geocode-extras.mjs [--dry-run] [--limit N]
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const OUT = resolve(ROOT, 'h5/src/data/extras-coords.js');

function loadEnvKey(name) {
  if (process.env[name]) return process.env[name];
  try {
    const p = resolve(ROOT, '.env');
    if (!existsSync(p)) return '';
    const line = readFileSync(p, 'utf8').split('\n').find((l) => l.startsWith(name + '='));
    return line ? line.slice(name.length + 1).trim() : '';
  } catch { return ''; }
}

async function geocode(key, query) {
  const url = `https://restapi.amap.com/v3/geocode/geo?address=${encodeURIComponent(query)}&city=${encodeURIComponent('武汉')}&key=${key}`;
  try {
    const res = await fetch(url);
    const j = await res.json();
    if (j.status !== '1' || !Array.isArray(j.geocodes) || !j.geocodes.length) return null;
    const g = j.geocodes[0];
    const [lng, lat] = (g.location || '').split(',').map(Number);
    if (!lng || !lat) return null;
    return { lng, lat, level: g.level || '', formatted: g.formatted_address || '' };
  } catch { return null; }
}

async function main() {
  const dryRun = process.argv.includes('--dry-run');
  const limitArg = process.argv.indexOf('--limit');
  const limit = limitArg >= 0 ? Number(process.argv[limitArg + 1]) : 0;

  // 直接读源数据（不依赖 all-merchants，避免循环依赖）；南湖缺坐标 = robin-99/web-stalls 南湖店
  const { robin99, toMerchantObjects: robinObjs } = await import('../h5/src/data/robin-99.mjs');
  const { webStalls, toMerchantObjects: webObjs } = await import('../h5/src/data/web-stalls.mjs');
  const extras = [...robinObjs(robin99), ...webObjs(webStalls)];
  const targets = extras.filter((m) => m.zone === '财大南湖周边' && typeof m.lng !== 'number');
  const list = limit > 0 ? targets.slice(0, limit) : targets;

  const key = loadEnvKey('AMAP_SERVER_KEY');
  if (!key) { console.error('缺少 AMAP_SERVER_KEY（.env）'); process.exit(1); }
  if (dryRun) {
    console.log(`[dry-run] 待补坐标南湖店 ${targets.length} 家（本次将处理 ${list.length} 家）`);
    console.log('地址样例:', list.slice(0, 5).map((m) => m.name + '|' + (m.address || '')).join(' ;; '));
    return;
  }

  const result = {};
  let ok = 0, fail = 0;
  for (let i = 0; i < list.length; i++) {
    const m = list[i];
    const query = (m.address || '').trim() || m.name;
    const g = await geocode(key, query);
    if (g) {
      result[m.name] = { lng: g.lng, lat: g.lat, coordsSource: 'geocode', query, level: g.level };
      ok++;
    } else {
      fail++;
      console.log(`  [跳过] ${m.name}（${query.slice(0, 24)}）`);
    }
    await new Promise((r) => setTimeout(r, 250)); // 节流，防配额
  }
  const payload = { version: 1, generatedAt: new Date().toISOString(), nanhu: result };
  // ESM 数据模块（与 robin-99.mjs 一致，可在浏览器与 node 同构 import）
  const moduleSrc = `// AUTO-GENERATED by scripts/geocode-extras.mjs — DO NOT EDIT BY HAND.\n// W3.1 南湖前端独有商户坐标补全（高德 geocode 真实坐标，coordsSource:'geocode' 审计标记）。\n// 生成时间 ${payload.generatedAt}\nexport const extrasCoords = ${JSON.stringify(payload)};\n`;
  writeFileSync(OUT, moduleSrc, 'utf8');
  console.log(`完成：成功 ${ok} / 失败 ${fail} / 共 ${list.length}`);
  console.log(`产物 -> ${OUT}`);
}

main().catch((err) => { console.error('错误:', err && err.message || err); process.exit(1); });
